### ISSUE TITLE
Parse Error?

### ISSUE THREAD

**Issue by sabret00the** [werdeil/clementine-last-export#15]
```
    raise err
xml.etree.ElementTree.ParseError: no element found: line 1065, column 58
```
I hope/think it's as simple as a sanitisation error that's easily fixed?

**Comment by werdeil** [comment]
Hi, I didn't manage to reproduce the issue, seems that Last.fm didn't send the playcount in the correct format, relaunching the tool should work. You may need to remove the extract_lastfm.txt file.
